In [53]:
import pandas as pd

##Reading Data

In [54]:
df=pd.read_csv('Data.csv')

In [55]:
df.head()

fever  bodypain  age  runnyNose  diffBreath  InfectionPro
0     98         0    2          0           1             1
1     98         0   24          1           0             1
2     99         0   28          1          -1             1
3    100         1   33          0           1             1
4    100         1   98          1           1             1

In [56]:
df.tail()

fever  bodypain  age  runnyNose  diffBreath  InfectionPro
2982     98         0   25          1           1             0
2983     98         0   25          0           1             0
2984    100         1   17          0           0             0
2985    100         1   50          0           1             0
2986     99         1   93          0           0             0

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2987 entries, 0 to 2986
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fever         2987 non-null   int64
 1   bodypain      2987 non-null   int64
 2   age           2987 non-null   int64
 3   runnyNose     2987 non-null   int64
 4   diffBreath    2987 non-null   int64
 5   InfectionPro  2987 non-null   int64
dtypes: int64(6)
memory usage: 140.1 KB


In [58]:
df['diffBreath'].value_counts()

diffBreath
-1    1013
 1     999
 0     975
Name: count, dtype: int64

In [59]:
df.describe()

fever     bodypain          age    runnyNose   diffBreath  \
count  2987.000000  2987.000000  2987.000000  2987.000000  2987.000000   
mean     99.004017     0.513894    50.015065     0.496820    -0.004687   
std       0.815529     0.499891    29.294829     0.500074     0.820847   
min      98.000000     0.000000     1.000000     0.000000    -1.000000   
25%      98.000000     0.000000    24.000000     0.000000    -1.000000   
50%      99.000000     1.000000    50.000000     0.000000     0.000000   
75%     100.000000     1.000000    75.000000     1.000000     1.000000   
max     100.000000     1.000000   100.000000     1.000000     1.000000   

       InfectionPro  
count   2987.000000  
mean       0.494476  
std        0.500053  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        1.000000  
max        1.000000

## Train Test Spliting

In [60]:
import numpy as np

In [61]:
def data_split(Data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(Data))
    test_set_size=int(len(Data)*ratio)
    test_indecies=shuffled[:test_set_size]
    train_indecies=shuffled[test_set_size:]
    return Data.iloc[train_indecies], Data.iloc[test_indecies]

In [62]:
np.random.permutation(7)

array([4, 6, 1, 5, 3, 0, 2])

In [63]:
train, test=data_split(df, 0.2)

In [64]:
train

fever  bodypain  age  runnyNose  diffBreath  InfectionPro
1206     99         0   97          0          -1             0
2020     98         1   72          1          -1             0
2627     98         0   54          0          -1             1
1979     99         1    9          0           1             1
612      98         0   69          0          -1             0
...     ...       ...  ...        ...         ...           ...
1638     98         0   99          0           1             0
1095     99         0   25          1          -1             1
1130    100         0   48          0          -1             1
1294    100         1   18          1           0             0
860      99         1   28          1           1             1

[2390 rows x 6 columns]

In [65]:
test

fever  bodypain  age  runnyNose  diffBreath  InfectionPro
2591     99         0   15          0           1             1
727      98         1   11          0          -1             1
1488    100         0   68          0           1             0
1517     99         0   89          1           0             1
1465     98         1   31          1           1             0
...     ...       ...  ...        ...         ...           ...
1494    100         0   34          0           0             1
212      98         0    6          1           0             0
12       98         0   13          0           1             0
1364    100         0   55          1           1             0
422      99         0   34          0           0             1

[597 rows x 6 columns]

In [66]:
x_train=train[['fever', 'bodypain', 'age', 'runnyNose', 'diffBreath']].to_numpy()
x_test=test[['fever', 'bodypain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [67]:
y_train=train[['InfectionPro']].to_numpy().reshape(2390,)
y_test=test[['InfectionPro']].to_numpy().reshape(597,)

In [68]:
y_train

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [69]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,

In [70]:
from sklearn.linear_model import LogisticRegression

In [71]:
clf=LogisticRegression()
clf.fit(x_train, y_train)

LogisticRegression()

In [74]:
inputFeature=[102,1,22,-1,1]
infPro=clf.predict_proba([inputFeature])[0][1]

In [75]:
infPro

0.48095417379427696